-- 不删除数据库
CREATE DATABASE IF NOT EXISTS `gpu_sharing_platform`;

USE `gpu_sharing_platform`;

DROP TABLE IF EXISTS `test_instance`;
CREATE TABLE IF NOT EXISTS `test_instance` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NULL,
    `created_at` TIMESTAMP DEFAULT NULL
);

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `role` VARCHAR(255) DEFAULT 'USER',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `pods`;
CREATE TABLE IF NOT EXISTS `pods` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `pod_name` VARCHAR(255) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `ssh_address` VARCHAR(255) NOT NULL ,
    `port_num` VARCHAR(255) NOT NULL ,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `ports`;
CREATE TABLE IF NOT EXISTS `ports` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `port_num` INT NOT NULL,  -- 存储端口号
    `status` INT NOT NULL,     -- 存储端口状态
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `ip_mapping`;
CREATE TABLE IF NOT EXISTS `ip_mapping` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `public_ip` VARCHAR(45) NOT NULL,  -- 存储公网 IP
    `private_ip` VARCHAR(45) NOT NULL,  -- 存储内网 IP
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

