-- 不删除数据库
CREATE DATABASE IF NOT EXISTS `gpu_sharing_platform`;

USE `gpu_sharing_platform`;

DROP TABLE IF EXISTS `test_instance`;
CREATE TABLE IF NOT EXISTS `test_instance` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NULL,
    `created_at` TIMESTAMP DEFAULT NULL
);

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `role` VARCHAR(255) DEFAULT 'user',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `pod`;
CREATE TABLE IF NOT EXISTS `pod` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `pod_name` VARCHAR(255) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);

